### ISSUE TITLE
unable to load CA private key

### ISSUE THREAD

**Issue by unibravo** [Alfresco/alfresco-ssl-generator#12]
MacAir:~ alf$ **./alfresco-ssl-generator-master/ssl-tool/run.sh**

ls: keystores: No such file or directory
Generating RSA private key, 1024 bit long modulus
...........................++++++
.....++++++
e is 65537 (0x10001)
Generating a 1024 bit RSA private key
.++++++
...............++++++
writing new private key to 'certificates/repository.key'
-----
Using configuration from openssl.cnf
Error opening CA private key ./demoCA/private/cakey.pem
4501907052:error:02FFF002:system library:func(4095):No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/crypto/bio/bss_file.c:255:fopen('./demoCA/private/cakey.pem', 'r')
4501907052:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/crypto/bio/bss_file.c:257:
unable to load CA private key
MacAir:~ alf$

**Comment by aborroy** [comment]
You need to run the command from the installation folder:

```
$ cd alfresco-ssl-generator-master/ssl-tool

$ ./run.sh
```
