### ISSUE TITLE
Generate for acs7 

### ISSUE THREAD

**Issue by 21Damien** [Alfresco/alfresco-ssl-generator#14]
Hello,

I generated keys with alfresco-ssl-generator.
When I specify alfrescoformat to current (ACS7) i have all my key/trust store

I had no problem with solr setting up TLS : i can put passwords in solr.in.sh and/or in the service's options.
I had a problem with alfresco to cummunicate with solr. In order to solve this problem i had to put in my alfresco-global.properties those two properties
```
encryption.ssl.keystore.keyMetaData.location 
encryption.ssl.truststore.keyMetaData.location 
```
But...  (this is the problem) the ssl generator doesn't deliver password.properties files. To solve that, i made a file with my favortie editor and it's works.
Is there any properties or Java arguments to put to specify keystore's password like a `encryption.ssl.keystore.password` and `encryption.ssl.truststore.password` ? 

Thank you

**Comment by aborroy** [comment]
When using the ACS 7 format, you don't need those files:
https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/docker-compose.yml#L18

```
JAVA_TOOL_OPTIONS: "
-Dencryption.keystore.type=JCEKS                
-Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding                
-Dencryption.keyAlgorithm=DESede                
-Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore                
-Dmetadata-keystore.password=mp6yc0UD9e                
-Dmetadata-keystore.aliases=metadata                
-Dmetadata-keystore.metadata.password=oKIWzVdEdA                
-Dmetadata-keystore.metadata.algorithm=DESede                
"
```

**Comment by 21Damien** [comment]
Thank you for your answer.
Those JAVA_TOOL_OPTIONS 
```
-Dmetadata-keystore.password=mp6yc0UD9e                
-Dmetadata-keystore.aliases=metadata                
-Dmetadata-keystore.metadata.password=oKIWzVdEdA                
-Dmetadata-keystore.metadata.algorithm=DESede    
```
Are already filled but i figure that they are defined for the keystore/keystore file. If my SSL keystores (mutual TLS acs and ass) have differents passwords. How can we do that ?

**Comment by aborroy** [comment]
Hope this helps:
https://github.com/aborroy/alfresco-solr-docker-mtls
https://github.com/aborroy/alfresco-mtls-tutorial
