### ISSUE TITLE
Encryption keystore format and Key algorithm wrong value when alfrescoformat is classic?

### ISSUE THREAD

**Issue by HarmonyCarlo** [Alfresco/alfresco-ssl-generator#6]
After downloading the installation zip for ACS 6.2.1 I tried to use the linux ssl generator but it was creating the wrong type of keystores. The type is always "PKCS12" and algorithm is also always "-keyalg AES -keysize 256" despite setting the  alfrescoformat to "classic".

After checking the bash run.sh script I saw that the setting of the Key algorithm (Line 100-105) and the Encryption keystore format set (Line 85-90) are outside of the generate function. So they will be executed BEFORE the parameters are loaded. 
Because the default ALFRESCO_FORMAT is initiated as "current"  the settings for "current" are always set in the two if else blocks.
I moved both if/else blocks in the top of the generate function and now the keystores are created correctly. 

Regards!
Carlo / Harmony group

**Comment by aborroy** [comment]
Thanks for your contribution. Proposed changes have been applied to the project.
